apiVersion: v1
kind: Service 
metadata:
  name: postgres-service
  namespace: harbor
  labels:
    app: postgres
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres
