apiVersion: v1
kind: Service 
metadata:
  name: postgres-headless-service 
  namespace: harbor
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    app: postgres

